### ISSUE TITLE
Client request for IPv6 OPC UA URI triggers assertion in proxyd

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-proxy#32]
Hello,

I have successfully connected the sample client from api/csharp/samples/opc-ua/test/Client/ through
this opc-ua-proxy by using an IPv4 OPC UA URI.
But if the IPv4 address URI is replaced with an IPv6 URI the proxyd program aborts due to an assertion:

```
Tue May  2 11:34:06 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_is_final_fragment: final 1, rx pk length 0, draining 0
Tue May  2 11:34:06 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_read: read_ok, used 338

Tue May  2 11:34:06 2017 (io_mqtt_connection_receive_message:564) [DEBUG] RECV [size: 00000334]
Tue May  2 11:34:06 2017 (io_iot_hub_umqtt_connection_on_receive:438) [INFO] IN: [PING]
Tue May  2 11:34:06 2017 (pal_getaddrinfo:941) [INFO] getaddrinfo for "fd00:42:2001:db8:206:71ff:fe33:f6", "4840"
Tue May  2 11:34:06 2017 (io_iot_hub_umqtt_connection_on_send:316) [INFO] OUT: [PING]
Tue May  2 11:34:06 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_is_final_fragment: final 1, rx pk length 0, draining 0
Tue May  2 11:34:06 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_read: read_ok, used 6

Tue May  2 11:34:06 2017 (io_mqtt_connection_handle_PUBLISH_ACK:606) [DEBUG] SENT [size: 00000591, took 19]
Tue May  2 11:34:07 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_is_final_fragment: final 1, rx pk length 0, draining 0
Tue May  2 11:34:07 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_read: read_ok, used 41

Tue May  2 11:34:07 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_is_final_fragment: final 1, rx pk length 0, draining 0
Tue May  2 11:34:07 2017 (pal_wsclient_lws_log:123) [DEBUG] lws_read: read_ok, used 435

Tue May  2 11:34:07 2017 (io_mqtt_connection_receive_message:564) [DEBUG] RECV [size: 00000431]
Tue May  2 11:34:07 2017 (io_iot_hub_umqtt_connection_on_receive:438) [INFO] IN: [LINK]
Tue May  2 11:34:07 2017 (pal_socket_open_by_name:969) [INFO] Resolving fd00:42:2001:db8:206:71ff:fe33:f6:4840...
Tue May  2 11:34:07 2017 (pal_getaddrinfo:941) [INFO] getaddrinfo for "fd00:42:2001:db8:206:71ff:fe33:f6", "4840"
Tue May  2 11:34:07 2017 (pal_getaddrinfo:965) [ERROR] getaddrinfo returned error 'Address family for hostname not supported' (-9)
Tue May  2 11:34:07 2017 (pal_os_to_prx_gai_error:39) [ERROR] [!!! ASSERT !!!] Unknown getaddrinfo os error

```

And in the debugger I see, the following:

```
#1  0x00007ffff7b8894c in pal_getaddrinfo (address=0x7fffec010eb4 "fd00:42:2001:db8:206:71ff:fe33:f6", service=0x7ffff291f990 "4840", family=prx_address_family_inet, flags=0, prx_ai=0x7fffec0111f8, prx_ai_count=0x7fffec011200) at /home/klj/iot-gateway-proxy/src/pal/pal_net_posix.c:966
966	            return pal_os_to_prx_gai_error(result);
#2  0x00007ffff7b8b610 in pal_socket_open_by_name (sock=0x7fffec010e90) at /home/klj/iot-gateway-proxy/src/pal/pal_sk_posix.c:972
972	        result = pal_getaddrinfo(
#1  0x00007ffff7b8894c in pal_getaddrinfo (address=0x7fffec010eb4 "fd00:42:2001:db8:206:71ff:fe33:f6", service=0x7ffff291f990 "4840", family=prx_address_family_inet, flags=0, prx_ai=0x7fffec0111f8, prx_ai_count=0x7fffec011200) at /home/klj/iot-gateway-proxy/src/pal/pal_net_posix.c:966
966	            return pal_os_to_prx_gai_error(result);
(gdb) print result
$1 = -9
(gdb) print service
$2 = 0x7ffff291f990 "4840"
(gdb) print hint
$3 = {ai_flags = 2, ai_family = 2, ai_socktype = 0, ai_protocol = 0, ai_addrlen = 0, ai_addr = 0x0, ai_canonname = 0x0, ai_next = 0x0}
```

So the problem is, that the address family is set to AF_INET and not to AF_UNSPEC (which would had allowed IPv6).

**Comment by marcschier** [comment]
I will close this one, I assume the workaround takes care of this.  If there is a better fix desired, please reopen.
